/* D&D 2024 Basic Rules - all 17 feats (origin, general, fighting style, epic boon). attackRelevant = affects attack/damage rolls or initiative.
   prerequisite: { minimum_level, feature_named, ability: { STR: 13, DEX: 13, any: true } }   repeatable: can be taken more than once.
   abilityIncrease: { amount, choose: [abilities] (pick one; 'any' = any ability), max } - Ability Score Improvement instead
   offers { options: [[2], [1, 1]], max: 20 } (+2 to one score or +1 to two).   choice: what the player picks (as in classes.js).
   aliases: other spellings to recognise on a sheet.
   Source: D&D Beyond Basic Rules (2024) / SRD 5.2.1 (CC-BY-4.0, see CREDITS.md). Numbers and names come from the
   rules data; feature text is condensed into short plain-language summaries (not the book text). */
window.DND = window.DND || {};

DND.feats = [
  {"name":"Alert","type":"origin","prerequisite":null,"attackRelevant":true,"summary":"Add your Proficiency Bonus to Initiative rolls; right after rolling you may swap Initiative with a willing ally (neither of you Incapacitated)."},
  {"name":"Magic Initiate","type":"origin","prerequisite":null,"attackRelevant":false,"repeatable":true,"summary":"Learn 2 cantrips and one level 1 spell from the Cleric, Druid or Wizard list (INT, WIS or CHA as the ability). The level 1 spell is always prepared and castable once per Long Rest without a slot. Swap one of these spells when you gain a level. Repeatable with a different list.","choice":{"type":"magicInitiate","lists":["cleric","druid","wizard"],"cantrips":2,"level1":1,"ability":["INT","WIS","CHA"]}},
  {"name":"Savage Attacker","type":"origin","prerequisite":null,"attackRelevant":true,"summary":"Once per turn when you hit with a weapon, roll its damage dice twice and use either roll."},
  {"name":"Skilled","type":"origin","prerequisite":null,"attackRelevant":false,"repeatable":true,"summary":"Proficiency in any combination of 3 skills or tools. Repeatable.","choice":{"type":"skillsOrTools","count":3}},
  {"name":"Ability Score Improvement","type":"general","prerequisite":{"minimum_level":4},"attackRelevant":false,"repeatable":true,"abilityIncrease":{"options":[[2],[1,1]],"max":20},"summary":"+2 to one ability score or +1 to two (max 20). Repeatable."},
  {"name":"Grappler","type":"general","prerequisite":{"minimum_level":4,"ability":{"STR":13,"DEX":13,"any":true}},"attackRelevant":true,"abilityIncrease":{"amount":1,"choose":["STR","DEX"],"max":20},"summary":"+1 STR or DEX (max 20). Once per turn an Unarmed Strike hit from the Attack action can both damage and grapple. Advantage on attacks against a creature you grapple; moving it costs no extra movement if it is your size or smaller."},
  {"name":"Archery","type":"fighting-style","prerequisite":{"feature_named":"Fighting Style"},"attackRelevant":true,"summary":"+2 bonus to attack rolls with Ranged weapons."},
  {"name":"Defense","type":"fighting-style","prerequisite":{"feature_named":"Fighting Style"},"attackRelevant":false,"summary":"+1 AC while wearing Light, Medium or Heavy armor."},
  {"name":"Great Weapon Fighting","type":"fighting-style","prerequisite":{"feature_named":"Fighting Style"},"attackRelevant":true,"summary":"When you roll damage for a Melee attack with a weapon held in two hands (it must have Two-Handed or Versatile), treat any 1 or 2 on a damage die as a 3."},
  {"name":"Two-Weapon Fighting","aliases":["Two Weapon Fighting"],"type":"fighting-style","prerequisite":{"feature_named":"Fighting Style"},"attackRelevant":true,"summary":"When you make the extra attack from a Light weapon, add your ability modifier to its damage if you aren't already."},
  {"name":"Boon of Combat Prowess","type":"epic-boon","prerequisite":{"minimum_level":19},"attackRelevant":true,"abilityIncrease":{"amount":1,"choose":"any","max":30},"summary":"+1 to one ability score (max 30). Peerless Aim: when you miss with an attack roll you can hit instead; once per turn (resets at the start of your next turn)."},
  {"name":"Boon of Dimensional Travel","type":"epic-boon","prerequisite":{"minimum_level":19},"attackRelevant":false,"abilityIncrease":{"amount":1,"choose":"any","max":30},"summary":"+1 to one ability score (max 30). Blink Steps: right after you take the Attack or Magic action, teleport up to 30 ft to an unoccupied space you can see."},
  {"name":"Boon of Fate","type":"epic-boon","prerequisite":{"minimum_level":19},"attackRelevant":false,"abilityIncrease":{"amount":1,"choose":"any","max":30},"summary":"+1 to one ability score (max 30). Improve Fate: when you or a creature within 60 ft succeeds or fails a D20 Test, roll 2d4 and add or subtract it; once per Initiative roll or Short or Long Rest."},
  {"name":"Boon of Irresistible Offense","aliases":["Boon of Irresistable Offense"],"type":"epic-boon","prerequisite":{"minimum_level":19},"attackRelevant":true,"abilityIncrease":{"amount":1,"choose":["STR","DEX"],"max":30},"summary":"+1 STR or DEX (max 30). Your bludgeoning, piercing and slashing damage ignores Resistance. On a 20 on an attack roll, deal extra damage equal to the score this boon raised."},
  {"name":"Boon of Spell Recall","type":"epic-boon","prerequisite":{"minimum_level":19,"feature_named":"Spellcasting"},"attackRelevant":false,"abilityIncrease":{"amount":1,"choose":["INT","WIS","CHA"],"max":30},"summary":"+1 INT, WIS or CHA (max 30). Free Casting: when you cast with a level 1-4 slot, roll 1d4; if it equals the slot's level, the slot isn't spent."},
  {"name":"Boon of the Night Spirit","type":"epic-boon","prerequisite":{"minimum_level":19},"attackRelevant":false,"abilityIncrease":{"amount":1,"choose":"any","max":30},"summary":"+1 to one ability score (max 30). In Dim Light or Darkness: Bonus Action to become Invisible (ends after you act), and Resistance to all damage except psychic and radiant."},
  {"name":"Boon of Truesight","type":"epic-boon","prerequisite":{"minimum_level":19},"attackRelevant":false,"abilityIncrease":{"amount":1,"choose":"any","max":30},"summary":"+1 to one ability score (max 30). Truesight 60 ft."}
];
